# name: Firefox Dev
# author: FredHappyface (https://github.com/fredHappyface)
# slug: firefox-dev
# slug-underscored: firefox_dev
# system: base24
# variant: dark

# Main bg
theme[main_bg]="#0e1011"

# Main text color
theme[main_fg]="#a5acae"

# Title color for boxes
theme[title]="#a5acae"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#359ddf"

# Background color of selected item in processes box
theme[selected_bg]="#002731"

# Foreground color of selected item in processes box
theme[selected_fg]="#a5acae"

# Color of inactive/disabled text
theme[inactive_fg]="#6e7d81"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#359ddf"

# Cpu box outline color
theme[cpu_box]="#5eb83c"

# Memory/disks box outline color
theme[mem_box]="#a57705"

# Net up/down box outline color
theme[net_box]="#d75cff"

# Processes box outline color
theme[proc_box]="#4b73a2"

# Box divider line and small boxes line color
theme[div_line]="#6e7d81"

# Temperature graph colors
theme[temp_start]="#5eb83c"
theme[temp_mid]="#006fc0"
theme[temp_end]="#e63853"

# CPU graph colors
theme[cpu_start]="#5eb83c"
theme[cpu_mid]="#006fc0"
theme[cpu_end]="#e63853"

# Mem/Disk free meter
theme[free_start]="#5eb83c"

# Mem/Disk cached meter
theme[cached_start]="#006fc0"

# Mem/Disk available meter
theme[available_start]="#a57705"

# Mem/Disk used meter
theme[used_start]="#e63853"

# Download graph colors
theme[download_start]="#5eb83c"
theme[download_mid]="#006fc0"
theme[download_end]="#e63853"

# Upload graph colors
theme[upload_start]="#5eb83c"
theme[upload_mid]="#006fc0"
theme[upload_end]="#e63853"
